from __future__ import annotations

from dataclasses import dataclass
from datetime import datetime


@dataclass(frozen=True, slots=True)
class Detection:
    """A single object detection from one frame."""
    bbox: tuple[int, int, int, int]  # x1, y1, x2, y2
    confidence: float
    class_name: str

    @property
    def centroid(self) -> tuple[int, int]:
        x1, y1, x2, y2 = self.bbox
        return ((x1 + x2) // 2, (y1 + y2) // 2)


@dataclass(frozen=True, slots=True)
class Track:
    """A tracked detection with a persistent ID across frames."""
    track_id: int
    detection: Detection

    @property
    def centroid(self) -> tuple[int, int]:
        return self.detection.centroid

    @property
    def bbox(self) -> tuple[int, int, int, int]:
        return self.detection.bbox

    @property
    def class_name(self) -> str:
        return self.detection.class_name

    @property
    def confidence(self) -> float:
        return self.detection.confidence


@dataclass(frozen=True, slots=True)
class Event:
    """An analytics event generated by the zone system."""
    timestamp: datetime
    event_type: str
    zone_name: str
    track_id: int
    object_class: str
    metadata: dict[str, object]
    confidence: float
    frame_snapshot: bytes
    bbox: tuple[int, int, int, int]


@dataclass(frozen=True, slots=True)
class FrameMeta:
    """Metadata about a video frame."""
    timestamp: datetime
    frame_index: int
    source_id: str
